/* Copyright (c) 2021 Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _CNSS_MODULE_H_
#define _CNSS_MODULE_H_

#ifdef CNSS_DISABLE_EXPORT_SYMBOL
#define cnss_export_symbol(sym)
#else
#define cnss_export_symbol(sym) EXPORT_SYMBOL(sym)
#endif

#define CNSS_PCI_DRIVER_DEFAULT_NAME		"cnss_pci"
#define PRE_ALLOC_DEBUGFS_DIR_DEFAULT_NAME	"cnss-prealloc"
#define IPC_ROUTER_DRIVER_DEFAULT_NAME		"ipc_router"
#define MSM_IPC_PROTO_DEFAULT_NAME		"MSM_IPC"
#define MHI_PCIE_DRIVER_DEFAULT_NAME		"mhi_pcie_drv"
#define MHI_BHI_CLASS_DEFAULT_NAME		"bhi"
#define MHI_DIR_DEFAULT_NAME			"mhi"
#define MHI_TRACE_SYSTEM_DEFAULT_NAME		mhi
#define IPC_ROUTER_SERVER_DEFAULT_FORMAT	"SVC%08x:%08x"

#define CNSS_STR(num) #num
#define CNSS_PCIE_SSID_STR(pcie_ssid) CNSS_STR(pcie_ssid)

#define MHI_TRACE_SYSTEM_NAME_ALIAS(suffix) mhi_##suffix
#define MHI_TRACE_SYSTEM_NAME_DECLARE(pcie_ssid) MHI_TRACE_SYSTEM_NAME_ALIAS(pcie_ssid)

#if defined(MULTI_CARD) && defined(PCIE_SSID) && defined(CUSTOM_FW_NL_PROTO) && defined(IPC_SOCKET_FAMILY)
#define QCA6490_SSID				PCIE_SSID
#define CNSS_PCI_DRIVER_NAME			CNSS_PCI_DRIVER_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define PRE_ALLOC_DEBUGFS_DIR_NAME		PRE_ALLOC_DEBUGFS_DIR_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define NETLINK_CUSTOM_FW_NUM			CUSTOM_FW_NL_PROTO
#define AF_MSM_IPC_NUM				IPC_SOCKET_FAMILY
#define IPC_ROUTER_DRIVER_NAME			IPC_ROUTER_DRIVER_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define MSM_IPC_PROTO_NAME			MSM_IPC_PROTO_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define MHI_PCIE_DRIVER_NAME			MHI_PCIE_DRIVER_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define MHI_BHI_CLASS_NAME			MHI_BHI_CLASS_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define MHI_DIR_NAME				MHI_DIR_DEFAULT_NAME "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define MHI_TRACE_SYSTEM_NAME			MHI_TRACE_SYSTEM_NAME_DECLARE(PCIE_SSID)
#define IPC_ROUTER_SERVER_FORMAT		IPC_ROUTER_SERVER_DEFAULT_FORMAT "_" CNSS_PCIE_SSID_STR(PCIE_SSID)
#define FW_PREFIX				"wlan/wlan_" CNSS_PCIE_SSID_STR(PCIE_SSID) "/"
#else
#define QCA6490_SSID				PCI_ANY_ID
#define CNSS_PCI_DRIVER_NAME			CNSS_PCI_DRIVER_DEFAULT_NAME
#define PRE_ALLOC_DEBUGFS_DIR_NAME		PRE_ALLOC_DEBUGFS_DIR_DEFAULT_NAME
#define NETLINK_CUSTOM_FW_NUM			27
#define AF_MSM_IPC_NUM				27
#define IPC_ROUTER_DRIVER_NAME			IPC_ROUTER_DRIVER_DEFAULT_NAME
#define MSM_IPC_PROTO_NAME			MSM_IPC_PROTO_DEFAULT_NAME
#define MHI_PCIE_DRIVER_NAME			MHI_PCIE_DRIVER_DEFAULT_NAME
#define MHI_BHI_CLASS_NAME			MHI_BHI_CLASS_DEFAULT_NAME
#define MHI_DIR_NAME				MHI_DIR_DEFAULT_NAME
#define MHI_TRACE_SYSTEM_NAME			MHI_TRACE_SYSTEM_DEFAULT_NAME
#define IPC_ROUTER_SERVER_FORMAT		IPC_ROUTER_SERVER_DEFAULT_FORMAT
#define FW_PREFIX				""
#endif
#endif
